apiVersion: v1
kind: Pod
metadata:
  name: pod1
  labels:
    tier: frontend
spec:
  containers:
    - name: app
      image: app:1.0.0
      imagePullPolicy: Never
---

apiVersion: v1
kind: Pod
metadata:
  name: pod2
  labels:
    tier: frontend
spec:
  containers:
    - name: app
      image: app:1.0.0
      imagePullPolicy: Never
