apiVersion: v1
kind: Service
metadata:
  name: app
  labels:
    app: app
spec:
  selector:
    app: app
  clusterIP: None
  ports:
  - name: default
    protocol: TCP
    port: 8080
    targetPort: 8080
---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: app
spec:
  selector:
    matchLabels:
      app: app
  serviceName: "app"
  replicas: 3
  template:
    metadata:
      labels:
        app: app
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: app
        image: app:1.0.3
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
          name: app