version: '3.8'
services:
  es01:
    image: es_analysis:7.8.0
    container_name: es01
    environment:
      - node.name=es01
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=es02
      - cluster.initial_master_nodes=es01,es02
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - node.max_local_storage_nodes=20
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - /tmp/elasticsearch:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - elastic
  es02:
    image: es_analysis:7.8.0
    container_name: es02
    environment:
      - node.name=es02
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=es01
      - cluster.initial_master_nodes=es01,es02
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - node.max_local_storage_nodes=20
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - /tmp/elasticsearch:/usr/share/elasticsearch/data
    networks:
      - elastic

networks:
  elastic:
    driver: bridge