apiVersion: v1
kind: Service
metadata:
  name: app-svc
spec:
  type: NodePort
  selector:
    app: app
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
    name: app-port
---

apiVersion: v1
kind: Pod
metadata:
  name: app
  labels:
    app: app
spec:
  containers:
  - name: app
    image: app:1.0.0
    imagePullPolicy: IfNotPresent
    ports:
    - containerPort: 8080
      name: app-port
      protocol: TCP
    # readinessProbe:
    #   tcpSocket:
    #     port: 8080
    #   initialDelaySeconds: 5
    #   periodSeconds: 10
    # livenessProbe:
    #   tcpSocket:
    #     port: 8080
    #   initialDelaySeconds: 15
    #   periodSeconds: 20
