apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
spec:
  replicas: 4
  selector:
    matchLabels:
      app: app
      tier: backend
  template:
    metadata:
      labels:
        app: app
        tier: backend
    spec:
      containers:
      - name: app
        image: app:1.0.0
        imagePullPolicy: IfNotPresent
        ports:
          - name: http
            containerPort: 8080
        resources:
          limits:
            cpu: 500m
          requests:
            cpu: 200m
