apiVersion: v1
kind: Service
metadata:
  name: my-app-server
spec:
  selector:
    app: app
  ports:
    - name: default
      protocol: TCP
      port: 8080
      targetPort: 8080

---
apiVersion: v1
kind: Pod
metadata:
  name: app
  labels:
    app: app
spec:
  containers:
    - name: app
      image: app:1.0.0
      imagePullPolicy: Never
      ports:
        - containerPort: 8080
