apiVersion: v1
kind: Service
metadata:
  name: app
  labels:
    run: app
spec:
  type: ClusterIP
  ports:
  - port: 8080
    nodePort: 31199
    targetPort: 80
    protocol: TCP
  selector:
    run: app
